display_name: bettbox+

icon: ./assets/images/icon.png

keywords:
  - bettbox+
  - Bettbox
  - Clash
  - ClashMeta
  - Proxy

generic_name: bettbox+

categories:
  - Network

startup_notify: true
startup_wm_class: com.appshub.bettboxplus

include: []