script_template: inno_setup.iss
app_id: 839C4643-D85E-4981-A179-BE70FE1PLUS2
app_name: Bettbox+
publisher: Bettbox+
publisher_url: https://github.com/Tiam9173/bettboxplus
display_name: Bettbox+
executable_name: Bettbox.exe
output_base_file_name: Bettbox+.exe
setup_icon_file: ..\windows\runner\resources\app_icon.ico
locales:
  - lang: zh
    file: ..\windows\packaging\exe\ChineseSimplified.isl
  - lang: en
privileges_required: admin